version: "3"

services:
    payload:
        image: node:20-alpine
        ports:
            - "3000:3000"
        volumes:
            - .:/home/node/app
            - node_modules:/home/node/app/node_modules
        working_dir: /home/node/app/
        command: sh -c "yarn install && yarn dev"

volumes:
    data:
    node_modules:
